title: つくーるMVのぷらぐいん
author: asparlose
baseurl: /mv-plugins

collections:
  x:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "x"
    values:
      layout: "plugin"
      auto_description: true

plugins:
  - jekyll-asciidoc
